### PR TITLE
run nixpkgs-fmt

### PR DESCRIPTION
**Pull request by QuantumCoded**
Please format your code.

\- With Love
Jeff

### CODE REVIEW

**Review by Skarlett — APPROVED** [review]

**Comment by Andy3153** [comment]
Usually I like formatting stuff the way I like manually, but this is not far from my style of formatting at all so I'm pretty open to doing it. A question though, can I make it stop doing this

```nix
module1 =
  {
    module2 =
      {
        enable = true;
      };
  };
```

and just make it keep it like this?
```nix
module1 =
{
  module2 =
  {
    enable = true;
  };
};
```

**Comment by QuantumCoded** [comment]
Typically like this:
```nix
module1 = {
  module2 = {
    enable = true;
  };
};
```
or this
```nix
module1.module2.enable = true;
```
Both of these should be accepted by nixpkgs-fmt.

**Comment by Andy3153** [comment]
I know most people use
```nix
module1 = {
  module2 = {
    enable = true;
  };
};
```
but this
```nix
module1 =
{
  module2 =
  {
    enable = true;
  };
};
```
is much more readable, to me, because the curly brackets are on the same indentation line. But, I find no point in doing
```nix
module1 =
  {
    module2 =
      {
        enable = true;
      };
  };
```
because that just wastes vertical space for no reason

**Comment by QuantumCoded** [comment]
The extra tab is to visually create a "block" of code that is underneath the `module1 =`.

This is more applicable in an example like this:
```nix
myValue = someFunc
  (a: b: c: /* some really large function body code here */)
  { a = 1; b = 2; c = 3; }
  [ 1 2 3 4 5 ];
  ```
The extra indentation helps to identify that all the following lines are a part of the `myValue` definition.

Whereas without this indentation the separation can get lost if lines are joined:
```nix
myValue1 = someFunc
(a: b: c: /* some really large function body code here */)
{ a = 1; b = 2; c = 3; }
[ 1 2 3 4 5 ];
myValue2 = someFunc
(a: b: c: /* some really large function body code here */)
{ a = 1; b = 2; c = 3; }
[ 1 2 3 4 5 ];
```
The lack of separation can muddle the code for the reader.

**Comment by Andy3153** [comment]
True, when what's in the curly brackets is all on one line like that, the indentation makes sense. But when a code block is an actual code block and not only a block all on one line, it looks weird. No way to get rid of that?

**Comment by QuantumCoded** [comment]
I disagree, I think the indentation, even on attrs, looks quite natural when needed.

If only an attrs is needed I would format like this:
```nix
myValue = myFunc {
  a = 1;
  b = 2;
  c = 3;
};
```
The extra tab is only really needed if there's multiple arguments:
```nix
myValue = myFunc
  "an extra argument"
  {
    a = 1;
    b = 2;
    c = 3;
  };
```

nixpkgs-fmt is really expecting you to hang the first `{` on the opening line instead of putting it on the line below.

i.e. using:
```nix
module1 = {
  module2 = {
    enable = true;
  };
};
```
over
```nix
module1 =
{
  module2 =
  {
    enable = true;
  };
};
```

It's going to try to treat the latter case as the example from earlier with multiple arguments and indent it like you were saying before:
```nix
module1 =
  {
    module2 =
    {
      enable = true;
    };
  };
```

**Comment by Andy3153** [comment]
Then.. what benefits am I getting from using `nixpkgs-fmt`? I am not completely sure I want that double indentation

**Comment by QuantumCoded** [comment]
The benefits you get from using `nixpkgs-fmt` (or any other Nix formatter, there's a few) is code consistency with the rest of the Nix ecosystem. `nixpkgs-fmt` is the formatter that's endorsed by `NixOS/nixpkgs` for use on the official `nixpkgs` repo, which is why I use it.

Having readable code helps others to collaborate more efficiently and creates a single or few standard(s) that everyone can use.

Here's a few formatters from [awesome-nix](https://github.com/nix-community/awesome-nix):
https://github.com/kamadorueda/alejandra - An opinionated Nix code formatter optimized for speed and consistency.
https://github.com/serokell/nixfmt - A formatter for Nix code, intended to easily apply a uniform style.
https://github.com/nix-community/nixpkgs-fmt - Nix code formatter for nixpkgs.

Edit:
If you don't want to worry about running a formatter all the time, you can also use GitHub to run a formatting CI action to give you a green check if your code is formatted correctly. It could even PR you with correctly formatted code.

On an unrelated note, you can also use this for building and caching your systems, checking your flake, etc. After this the typical workflow goes make a `dev` branch, work exclusively on that, then open a PR from `master <- dev` and then only merge the PR when the CI checks pass. Then your `master` branch cannot have incorrectly formatted code; branch protection also goes into this to ensure no pushing to `master` directly.

Edit (x2):
Just remembered you can also use a git pre-commit hook to run the formatter before you push you code.

**Comment by Andy3153** [comment]
@QuantumCoded I made an issue to discuss the behavior of nixpkgs-fmt and not respecting Allman-style code formatting and I'll begin using a formatter if I get a response. I'm thinking of using nixpkgs-fmt when/if they make a change to it right inside Neovim. But if it takes way too long to get an answer I'll probably settle for Alejandra and git pre-commit hooks like you've said

**Pull request closed without merging**
